In [2]:
import numpy as np

## add, subtract, multiple, divide, exponent

In [7]:
arr = np.arange(1, 11);
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [8]:
# multiply each element by itself
arr * arr

array([  1,   4,   9,  16,  25,  36,  49,  64,  81, 100])

In [9]:
# add each element to itself
arr + arr

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [10]:
# subtract each element from itself
arr - arr

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [11]:
# divide each element by itself
arr / arr

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [12]:
# multiply a scalar value to array elements
5 * arr

array([ 5, 10, 15, 20, 25, 30, 35, 40, 45, 50])

In [14]:
# add a scalar value to array elements
1 + arr

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [15]:
# subtract a scalar value from array elements
arr - 1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [16]:
# divide each array elements by a scalar value
arr / 2

array([0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5, 5. ])

In [17]:
# raise each element of the array by 2
arr ** 2

array([  1,   4,   9,  16,  25,  36,  49,  64,  81, 100])