In [47]:
import numpy as np

## 1d array

In [86]:
arr_list = [10, 20, 30]
arr = np.array(arr_list)
arr

array([10, 20, 30])

## 2d array

In [87]:
arr_2d = [
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
]
arr = np.array(arr_2d)
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

## 1d array using `arange()`

In [52]:
np.arange(0, 10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [53]:
# create array of odd numbers
np.arange(1, 10, 2)

array([1, 3, 5, 7, 9])

In [54]:
# create array of even numbers
np.arange(0, 10, 2)

array([0, 2, 4, 6, 8])

## 1d array using `zeros()` and `ones()`

In [55]:
# create array filled with zeros
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [56]:
# create array filled with ones
np.ones(5)

array([1., 1., 1., 1., 1.])

## 2d array using `zeros()` and `ones()`

In [57]:
# create 2d array having 2 rows and 3 columns and fill it with zeros
np.zeros((2, 3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [58]:
# create 2d array having 3 rows and 3 columns and fill it with ones
np.ones((3, 3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

## create array having equally spaced elements

In [59]:
# create an 1d array having 5 equally spaced numbers between 0 and 10.
np.linspace(0, 10, 5)

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

## create identity matrix

In [60]:
# create a 4x4 identity matrix
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

## create array filled with random numbers from a uniform distribution between 0 and 1

In [61]:
# create an 1d array having 10 elements uniformally distributed between 0 and 1
np.random.rand(10)

array([0.5910472 , 0.32966342, 0.55715485, 0.10323663, 0.53670446,
       0.93930957, 0.90509462, 0.13972847, 0.54977689, 0.82854503])

In [62]:
# create a 2d array having 2 rows and 3 columns and filled with uniformally distributed numbers betweem 0 and 1
np.random.rand(2, 3)

array([[0.02576343, 0.50019147, 0.57380709],
       [0.7889919 , 0.48312402, 0.67542072]])

## create array filled with random numbers from a standard normal distribution between 0 and 1

In [63]:
# create an 1d array having 10 elements and filled with normal distribution number between 0 and 1
np.random.randn(10)

array([-0.76115095, -0.26042222, -0.4414572 , -1.18509389, -0.07083081,
       -0.4120991 , -0.91208843, -0.39256069, -0.69392368,  2.01741854])

In [68]:
# create a 2d array having 2 rows and 3 columns and fill it with normal distribution number between 0 and 1
np.random.randn(2, 3)

array([[-0.68157095, -0.99701994, -0.6661533 ],
       [-0.12011607,  0.59210615,  1.07941804]])

## get random integer

In [69]:
# random integer between 1 and 100
np.random.randint(1, 100)

96

In [71]:
# get 13 random numbers between 1 and 52
low = 1
high = 53
np.random.randint(low, high, 13)

array([17, 36, 37, 38, 26,  6, 38, 42,  3, 52, 24, 19, 42])

In [75]:
# create 3x3 random numbers matrix
np.random.randint(0, 10, 9).reshape(3, 3)

array([[1, 0, 2],
       [5, 5, 6],
       [3, 4, 3]])

## min max

In [81]:
# generate 10 random integers
random_arr = np.random.randint(1, 100, 10)
random_arr

array([58, 83, 39, 71, 72, 81, 10, 81, 26, 96])

In [82]:
# get maximum value
np.max(random_arr)

96

In [83]:
# get minimum value
np.min(random_arr)

10

In [84]:
# get maximum value's index
np.argmax(random_arr)

9

In [88]:
# get minimum value's index
np.argmin(random_arr)

6

## slice array

In [90]:
# slice 1d array and return a subarray
arr = np.array([0, 10, 20, 30, 40, 50, 60, 70, 80])
arr[0:5]

array([ 0, 10, 20, 30, 40])

In [91]:
# slice 2d array and return a 2d subarray
arr = np.array([
    [10, 20, 30],
    [40, 50, 60],
    [70, 80, 90]
])
arr[0:2, 0:1]

array([[10],
       [40]])