In [1]:
import numpy as np

## 1d array

In [4]:
arr_list = [10, 20, 30]
arr = np.array(arr_list)

In [5]:
arr

array([10, 20, 30])

## 2d array

In [6]:
arr_2d = [
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
]
arr = np.array(arr_2d)

In [7]:
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

## 1d array using `arange()`

In [8]:
np.arange(0, 10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [11]:
# create array of odd numbers
np.arange(1, 10, 2)

array([1, 3, 5, 7, 9])

In [12]:
# create array of even numbers
np.arange(0, 10, 2)

array([0, 2, 4, 6, 8])

## 1d array using `zeros()` and `ones()`

In [15]:
# create array filled with zeros
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [16]:
# create array filled with ones
np.ones(5)

array([1., 1., 1., 1., 1.])

## 2d array using `zeros()` and `ones()`

In [24]:
# create 2d array having 2 rows and 3 columns and fill it with zeros
np.zeros((2, 3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [25]:
# create 2d array having 3 rows and 3 columns and fill it with ones
np.ones((3, 3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

## create array having equally spaced elements

In [22]:
# create an 1d array having 5 equally spaced numbers between 0 and 10.
np.linspace(0, 10, 5)

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

## create identity matrix

In [23]:
# create a 4x4 identity matrix
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

## create array filled with random numbers from a uniform distribution between 0 and 1

In [31]:
# create an 1d array having 10 elements uniformally distributed between 0 and 1
np.random.rand(10)

array([0.59458202, 0.09323539, 0.88058264, 0.97761673, 0.96674211,
       0.85859785, 0.16941162, 0.47286892, 0.1496852 , 0.46854726])

In [29]:
# create a 2d array having 2 rows and 3 columns and filled with uniformally distributed numbers betweem 0 and 1
np.random.rand(2, 3)

array([[0.2458882 , 0.91449638, 0.96180022],
       [0.20699271, 0.02328959, 0.3785197 ]])

## create array filled with random numbers from a standard normal distribution between 0 and 1

In [32]:
# create an 1d array having 10 elements and filled with normal distribution number between 0 and 1
np.random.randn(10)

array([ 1.55594638,  0.72294538, -1.80050104,  2.20369418,  0.98081671,
        0.94403949,  1.27353453,  0.02354728,  0.86563321, -0.53704208])